name: contruir imagen y subirla a dockerhub

on: 
    push:
        branches:["main"]
    pull_request:
        branches:["main"]
  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
              -uses: action/checkout@v3
              -name: login en Docker Hub
              -uses: docker/login-in-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}
              -name: preparar construcion con docker buildx
              -uses: docker/setup-build-action@v2
              name: construir imagen y subirla a dockerhub
              -uses: docker/build-build-action@v4
              widht:
              context: .
              file: ./Docker
              push: true
              tags: |
                ${{ secrets.DOCKER_USERNAME }}/docker-github-actions:latest
                ${{ secrets.DOCKER_USERNAME }}/docker-github-actions ${{ github.sha }}
